[package]
name = "eth_cracker"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0", features = ["ws", "rustls"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
rayon = "1.5"
dotenv = "0.15"
chrono = "0.4"
serde_json = "1.0"